[pytest]
addopts = -v --alluredir=allure-results -n auto
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
markers =
    ui: UI-тесты (часто медленные, можно отключать с -m "not ui")
    smoke: Smoke-тесты (быстрая проверка ключевых сценариев)
    regression: Регрессионные тесты (полный набор позитивных и негативных кейсов)
